### ISSUE TITLE
arbitrary URLs

### ISSUE THREAD

**Issue by derekmoyes** [objectrocket/opsy#129]
Add a feature for arbitrary URLs, which can be used to link to documentation, or other sources.

**Comment by cryptk** [comment]
Do you mean in the top menu bar?  If so, that is such a great idea that David and I had actually already talked about doing that :P But the issue will definitely make sure that we don't forget about it.

**Comment by testeddoughnut** [comment]
I would like to see this implemented at the check level, maybe by having some metadata associated with the check in sensu/nagios that opsy can pick up on.

**Comment by cryptk** [comment]
as part of #184 I plan to detect links in the check output and make them clickable, so as long as the check returns a URL, you will be able to click it.

**Comment by cryptk** [comment]
Links in the output field are now clickable.  I can add more fields to get autolinking if necessary.

**Comment by testeddoughnut** [comment]
I need to make metadata tables for the various entities in the monitoring plugin. Hoping to have this out by next milestone.
