### ISSUE TITLE
graph embeds

### ISSUE THREAD

**Issue by derekmoyes** [objectrocket/opsy#130]
Add a feature to allow graphite/grafana embedded graphs in a page.

**Comment by testeddoughnut** [comment]
Depending on how this is implemented, #15 is probably a blocker.

**Comment by cryptk** [comment]
I don't think that this depends on #15.  We should just be able to have an entry in the check return that points to a graphite graph.  If the front-end see's an item named "embed_url" or something like that, then it will attempt to embed that URL into the details page.  Should be front-end only.  I am going to tag this one for v0.2, but it might slip to v0.3...
