### ISSUE TITLE
"check" zones for a dashboard instead of hiding them

### ISSUE THREAD

**Issue by derekmoyes** [objectrocket/opsy#131]
It would be nice if, when a dashboard was selected, the zones that don't exist in that dashboard were not hidden. One way to accomplish this would be to simply check all the included zones, and leave the not included zones unchecked. This could be replicated for other drop downs as well, such as Checks.

**Comment by cryptk** [comment]
I am removing the Needs API tag from this.  I am pretty sure that I can do this in the front-end with just the API endpoints that we currently have.  I would just need to populate the list from the main list, and then pre-select the ones from the dashboard specific list.
