### ISSUE TITLE
Turn on Silenced checkboxes...

### ISSUE THREAD

**Issue by derekmoyes** [objectrocket/opsy#182]
Maybe turn on Silenced checkboxes until we have preference saving?

**Comment by cryptk** [comment]
Authentication should be coming in v0.2, and along with that (because we will have a concept of users) will be preference saving.  That said, I have assigned this issue to the v0.2 milestone.

**Comment by testeddoughnut** [comment]
Auth being pushed back to v0.3, changing milestones on this.
