### ISSUE TITLE
Source icon 'u' improvements

### ISSUE THREAD

**Issue by derekmoyes** [objectrocket/opsy#200]
'u' (source icon) from the Events page is in the 'Source' column, but actually links to the alerting check page on the source dashboard.

I suggest moving the icon to the 'output' column, or 
remove it from the Events page altogether and add it to the clients and check page, or 
do both (move it and add it).

**Comment by cryptk** [comment]
PR merged, will go out when the next release is cut

**Comment by derekmoyes** [comment]
The above PR fixes the Events page. The source icon should still be added to the Clients page and the Check page.

**Comment by testeddoughnut** [comment]
This feature was added in #208. Has not been merged to master yet.
