### ISSUE TITLE
User settings storage

### ISSUE THREAD

**Issue by cryptk** [objectrocket/opsy#212]
Once we have authentication, it would be nice to have an API endpoint where arbitrary user setting_name value pairs could be stored.  It needs to be an authenticated endpoint so that only a given user can change their own settings.  This will allow the UI to store preference changes that the user makes.

**Comment by testeddoughnut** [comment]
probably /api/users/username/settings

**Comment by cryptk** [comment]
sounds good.  Supporting the folowing syntaxes would probably be a good start

GET /api/users/settings - return all settings {'setting1': 'foo', 'setting2': 'bar', 'setting3': 'baz'}
GET /api/users/settings?values=setting2 - return single setting {'setting2': 'bar'}
GET /api/users/settings?values=setting2,setting3 - return both setting2 and 3
POST /api/users/settings POSTDATA {'setting2': 'quz'} - Create/Update one (or more) settings
DELETE /api/users/settings?values=setting2,setting3 - Remove user custom settings

We can modify that as needed, but I think that functionality would probably get me pretty close to 100% of what I would need for the UI

**Comment by testeddoughnut** [comment]
Done already, closing.
